### PR TITLE
Cache dependencies (Composer)

### PR DESCRIPTION
**Pull request by jmauerhan**

### CODE REVIEW

**Comment by bkuhl** [comment]
This is odd... it's failing with no log output.

**Comment by jmauerhan** [comment]
I noticed that, going to try closing and re-opening. I wish travis had a re-run button like circle-ci does.

**Comment by bkuhl** [comment]
It does have that (maybe just for admins?).  I tried it though with the same result.  Looking at the docs, I didn't see anything that needed to be done on the backend for caching.  Did I miss something?

**Comment by jmauerhan** [comment]
Nope, all that has to be done is adding the directive. And yeah I don't see the re-run button so must be an admin only thing. Anyway, it seems to have failed again. The config file looks correct. We may need to open a ticket with travis since you got the same result.

**Comment by bkuhl** [comment]
Travis provided this URL for tracking part of the issue: https://www.traviscistatus.com/incidents/lp492hx0z1my

**Comment by jmauerhan** [comment]
Looks like the log finally loaded, the docker login command failed.

**Comment by bkuhl** [comment]
I think Jason changed that this weekend, so we'll have to get the new password from him.  //cc @mabon

**Comment by mabon** [comment]
Changed what? All I did was adjust the team makeup on the property=os org and gave more access to more people on our teams. Nothing with the docker_username/password keyed into travis. Could it be anything else?

**Pull request closed without merging**
