### PR TITLE
Directory guidiance for different types of tests

### PR DESCRIPTION
**Pull request by bkuhl**
Breaks tests up into several directories to provide guidiance on where different types of tests should go

### CODE REVIEW

**Comment by bkuhl** [comment]
This PR is ready for review

**Comment by jlaswell** [comment]
We sure we want to keep the QuoteTest in the unit directory, since it exercises routes?

**Comment by bkuhl** [comment]
Nope, that was a mistake.  I've updated it.

**Comment by jlaswell** [comment]
LGTM

Merge at will!

**Pull request merged**
