### PR TITLE
Http to https redirect

### PR DESCRIPTION
**Pull request by bkuhl**
* Upgraded nginx to 1.11
 * nginx config is now generated allowing it to utilize environment variables
 * `production` and `staging` environments are redirected to https
 * supports ssl redirecting sitting behind HAProxy and ELB
 * `/healthcheck` endpoint is not redirected to https - contributed by @millidavids

### CODE REVIEW

**Comment by bkuhl** [comment]
I should have also mentioned that with this PR, nginx containers now require `APP_URL` and `APP_ENV` environment variables as shown in the Rancher deploy example.

**Comment by bkuhl** [comment]
Build is now passing

**Comment by jlaswell** [comment]
LGTM

Great work getting this up and running!

**Comment by AnitaYip** [comment]
I have trouble getting this to work on master-property-api, so temporarily going back to the older version of nginx/default.conf

Here is the failed build - https://travis-ci.com/realpage-property-os/master-property-api/builds/30872246  (you can see the error I am getting when the dredd tests try to invoke the API endpoints)

nginx is throwing an error that I couldn't figure out where to look for. So, if you have any pointers, let me know

**Comment by bkuhl** [comment]
That isn't an issue with the starter, but an issue with `master-property-api`.  I'd recommend running a diff between that repo and this repo to determine what's different in `master-property-api`.

**Pull request merged**
