### PR TITLE
no longer run composer as root

### PR DESCRIPTION
**Pull request by bkuhl**

### CODE REVIEW

**Comment by bkuhl** [comment]
Because `root` is no longer running composer, there's less risk associated with pulling in composer without checking the hash.  Doing so prevents teams from experiencing random CI failures due to an outdated composer hash.

// cc @meareg @mabon @AnitaYip

**Comment by jlaswell** [comment]
lgtm

**Comment by bkuhl** [comment]
Hold on merging this, there's a permissions issue locally.

**Comment by bkuhl** [comment]
We're leaving this PR open until the new Docker client comes out to replace Docker Toolbox.

**Pull request closed without merging**
