### PR TITLE
Commit changes, don't tag original container state

### PR DESCRIPTION
**Pull request by jlaswell**
Original state of `docker run` was kept when tagging container. We now commit the diff between the original state and the testing, cleanup, and mounting that happens via `docker-compose`.

@millidavids @bkuhl

### CODE REVIEW

**Comment by millidavids** [comment]
Looking good. +1

**Comment by bkuhl** [comment]
Are you saying this will commit the changes that take place within CI to the container that gets pushed?

**Comment by jlaswell** [comment]
@bkuhl Yea.

**Comment by bkuhl** [comment]
In CI we run unit tests... does this mean anything that composer dev dependencies are being deployed with the app?

**Comment by millidavids** [comment]
Uhhhhhhh, I misunderstood what commit did. I'm not sure that is what we want.

**Comment by jlaswell** [comment]
Well, this will at least give us insight into if our directories make it all the way to the final container. We can always add another line for `composer install --no-dev` at the end of the CI process.

**Comment by bkuhl** [comment]
I think we had previously agreed that we would maintain a perspective that the dockerfiles would build the production containers and anything needed for dev would be done within CI.  Is there something missing from the Dockerfile that is driving the need behind this?

**Comment by jlaswell** [comment]
Yea, the Dockerfile doesn't add the nginx configuration to the container, but we do mount that file via docker-compose. We can adjust the Dockerfile to copy that config over, but then devs will need to rebuild their container every time the make changes to nginx configurations.

**Comment by millidavids** [comment]
I am ok with that. I don't think nginx configuration will happen all that often.

**Comment by bkuhl** [comment]
I believe even if the `Dockerfile` mounts a file, `docker-compose` will overwrite the existing file system with volumes.  So in this case as long as compose continues to mount the file/directory correctly I don't think it'll require a rebuild.

**Comment by bkuhl** [comment]
Based on order of events, I think the container should be fully built (i.e. - nginx has the vhost on it) and then that directory/file is replaced when compose brings along a volume.

**Comment by jlaswell** [comment]
kk. We may still need to make a commit on the php containers due to permission issues with the storage directory too. I'll have to look into if we can solve that both locally and in CI.

**Pull request merged**
